spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://postgres:5432/booking_db
    username: booking_user
    password: booking_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8080
  address: 0.0.0.0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.booking: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.springframework.jdbc: DEBUG